name: example
description: A example of mono_kit.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mono_kit:
    git:
      url: https://github.com/mono0926/flutter_mono_kit.git
      ref: develop
  simple_logger: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true