name: example
description: A example of mono_kit.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mono_kit:
    path: ..
  simple_logger: ^1.5.1
  provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
dependency_overrides:
  provider:
    git:
      url: https://github.com/rrousselGit/provider.git
      ref: extensions
flutter:
  uses-material-design: true
  assets:
    - assets/images/