name: example
description: A example of mono_kit.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  mono_kit:
    path: ..
  simple_logger:
  provider:
  recase:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
dependency_overrides:
  provider: ^4.1.0-dev
flutter:
  uses-material-design: true
  assets:
    - assets/images/