name: mono_kit
description: A collection of convenient widgets and utils made by mono. Under construction now.
version: 0.12.3
homepage: https://github.com/mono0926/flutter_mono_kit
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.3
  rxdart: ^0.23.1
  url_launcher: ^5.4.0
  disposable_provider: ^2.1.0
  nested: ^0.0.4
  subscription_holder: ^1.0.0
  simple_logger: ^1.5.1
  tinycolor: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  plugin:
    platforms:
      android:
        package: com.mono0926.mono_kit
        pluginClass: MonoKitPlugin