name: mono_kit
description: A collection of convenient widgets and utils made by mono. Under construction now.
version: 0.9.1+1
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/flutter_mono_kit
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.1
  rxdart: ^0.22.1
  url_launcher: ^5.1.2
  disposable_provider: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.mono0926.mono_kit
    pluginClass: MonoKitPlugin