name: mono_kit
description: A collection of convenient widgets and utils made by mono. Under construction now.
version: 0.15.1
homepage: https://github.com/mono0926/flutter_mono_kit
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ">=0.7.0 <2.0.0"
  device_simulator: ^0.9.6
  flutter_cache_manager: ^1.4.0
  image_picker: ^0.6.7+1
  rxdart: ^0.24.1
  url_launcher: ^5.4.10
  disposable_provider: ^2.2.0
  freezed_annotation: ^0.7.1
  nested: ^0.0.4
  provider: ^4.1.3
  quiver: ^2.1.3
  stream_transform: ^1.2.0
  subscription_holder: ^2.0.0+1
  simple_logger: ^1.7.0
  tinycolor: ^1.0.2
  flutter_svg: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  pedantic_mono:
flutter:
  plugin:
    platforms:
      android:
        package: com.mono0926.mono_kit
        pluginClass: MonoKitPlugin
      ios:
        pluginClass: MonoKitPlugin
      macos:
        pluginClass: MonoKitPlugin