name: mono_kit
description: A collection of convenient widgets and utils.
version: 0.0.1
author:
homepage:
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  rxdart: ^0.22.0
  flutter_cache_manager: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: