name: mono_kit
description: A collection of convenient widgets and utils made by mono. Under construction now.
version: 0.14.0-dev+16
homepage: https://github.com/mono0926/flutter_mono_kit
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.3
  rxdart: ^0.23.1
  url_launcher: ^5.4.1
  disposable_provider: ^2.1.1
  nested: ^0.0.4
  provider: ^4.1.0-dev
  subscription_holder: ^1.2.0+1
  simple_logger: ^1.6.0+1
  tinycolor: ^1.0.2
  flutter_svg: ^0.17.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  plugin:
    platforms:
      android:
        package: com.mono0926.mono_kit
        pluginClass: MonoKitPlugin
      ios:
        pluginClass: MonoKitPlugin
      macos:
        pluginClass: MonoKitPlugin